name: "🐞 Bug Report"
description: Create a report to help us improve the project
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - xfox111
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: desc
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: e.g. The calendar is empty, even though timetable for my group is published.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction steps
      description: Precisely describe minimal number of steps that make the bug to appear
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See '...'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: e.g. My timetable should be displayed in the calendar.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshot
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser name
      placeholder: e.g. Google Chrome
    validations:
      required: true

  - type: input
    id: calendar
    attributes:
      label: Calendar service
      placeholder: e.g. Google Calendar, Outlook, etc.
    validations:
      required: true

  - type: input
    id: group
    attributes:
      label: Faculty, course number and group number
      description: |
        If you don't want to share your group publicly, say "PM", and send it to feedback@xfox111.net. Reference the issue number.
      placeholder: e.g. РТС, 2, РТ-31м
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: dropdown
    id: requested-help
    attributes:
      label: Are you willing to submit a PR for this issue?
      options:
        - "yes"
        - "no"
    validations:
      required: true

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
          required: true
        - label: The provided reproduction is a minimal reproducible example of the bug.
          required: true
