@Host = http://localhost:8080

GET {{Host}}/health
Accept: application/json

###

GET {{Host}}/stats
Accept: application/json

###

GET {{Host}}/faculties
Accept: application/json

###

GET {{Host}}/groups
	?facultyId=56682
	&year=2
Accept: application/json

###

@groupId = 56606
@facultyId = 50029
GET {{Host}}/timetable/{{facultyId}}/{{groupId}}
	?id=download
Accept: text/calendar

# id parameter changes behavior for the calendar:
# - If set to "download", nothing changes
# - If not present, an additional event will be appended to the calendar (see Program.cs)
# - If set to any other value, this request will be counted in active users stats (only once per ID until the next restart)
